"""Resets local demo data and seeds a known marketplace scenario.
It preserves any non-demo counteroffers by carrying them across the reset.
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
import json
from pathlib import Path

from alembic import command
from alembic.config import Config
from sqlalchemy import func, select
from sqlalchemy.exc import OperationalError
from sqlalchemy.orm import Session

import app.models as models_registry
from app.core.visibility import ListingVisibility
from app.core.config import get_settings
from app.db.base import Base
from app.db.seed import SEEDED_ACCOUNTS, run_seed
from app.db.session import get_engine, get_session_factory
from app.models.account import Account
from app.models.challenge import Challenge
from app.models.listing import PublicListingRecord
from app.models.service_expense import ServiceExpense
from app.services.challenges.submit import submit_challenge
from app.services.evidence.refresh import get_or_refresh_challenger_evidence
from app.services.listings.create import build_scope_version, create_listing_draft
from app.services.listings.projection import build_payload_hash, build_public_listing
from app.services.listings.types import PublishChoices
from app.services.listings.visibility import publish_listing
from app.services.transactions.import_run import run_import



def main() -> None:
    """Reset demo data, seed the marketplace loop, and print a summary."""

    engine = get_engine()
    session_factory = get_session_factory()
    preserved_accounts, preserved_challenges = _capture_preserved_counteroffers(session_factory())
    _ = models_registry

    Base.metadata.drop_all(bind=engine)
    engine.dispose()
    _remove_local_sqlite_file()
    _upgrade_schema_to_head()

    db = session_factory()
    try:
        run_seed(db)
        _restore_preserved_accounts(preserved_accounts, db)
        import_result = run_import("acc_owner_1", "fixture_apex_main", db)
        expense = db.scalar(
            select(ServiceExpense).where(ServiceExpense.normalized_vendor == "Sparkle Clean")
        )
        if expense is None:
            raise RuntimeError("Sparkle Clean expense was not generated by the import pipeline")

        scope = build_scope_version(
            expense.id,
            {
                "service_area": "San Francisco Bay Area",
                "location_approximate": "San Francisco, CA",
                "square_footage": 8000,
                "visit_frequency": "3x weekly",
                "bathroom_count": 4,
                "required_tasks": json.dumps(["vacuum", "trash", "restrooms"]),
                "supplies_included": True,
                "equipment_included": True,
                "taxes_included": True,
                "current_price_minor": 240000,
                "current_price_currency": "USD",
                "billing_cadence": "monthly",
                "challenge_deadline": datetime.now(timezone.utc) + timedelta(days=14),
                "incumbent_vendor_name": "Sparkle Clean",
            },
            db,
        )
        choices = PublishChoices(bidding_mode="open")
        listing = create_listing_draft(expense, scope, choices, db)
        db.commit()
        db.refresh(listing)
        preview = build_public_listing(listing, expense, scope, choices)
        publish_listing(
            expense_id=expense.id,
            scope_version_id=scope.id,
            choices=choices,
            previewed_payload_hash=build_payload_hash(preview),
            acting_account_id="acc_owner_1",
            db=db,
        )

        seeded_demo_ids = _seed_demo_challenges(listing.id, db)
        preserved_count = _restore_preserved_challenges(listing.id, scope.id, preserved_challenges, db)
        evidence_count = _refresh_all_evidence(seeded_demo_ids, db)

        listing_record = db.get(PublicListingRecord, listing.id)
        print(
            json.dumps(
                {
                    "accounts_seeded": int(db.scalar(select(func.count()).select_from(Account)) or 0),
                    "transactions_imported": import_result.new,
                    "listing_id": listing.id,
                    "listing_visibility": listing_record.visibility if listing_record else ListingVisibility.public.value,
                    "demo_challenges_seeded": len(seeded_demo_ids),
                    "preserved_genuine_counteroffers": preserved_count,
                    "evidence_records_refreshed": evidence_count,
                    "total_challenges": int(
                        db.scalar(
                            select(func.count()).select_from(Challenge).where(
                                Challenge.listing_id == listing.id
                            )
                        )
                        or 0
                    ),
                },
                indent=2,
            )
        )
    finally:
        db.close()


def _upgrade_schema_to_head() -> None:
    """Recreate the schema through Alembic so demo state matches migrations."""

    backend_dir = Path(__file__).resolve().parents[2]
    config = Config(str(backend_dir / "alembic.ini"))
    config.set_main_option("script_location", str(backend_dir / "alembic"))
    command.upgrade(config, "head")


def _remove_local_sqlite_file() -> None:
    """Remove the local SQLite database file so Alembic can recreate it cleanly."""

    database_url = get_settings().database_url
    if not database_url.startswith("sqlite:///"):
        return

    backend_dir = Path(__file__).resolve().parents[2]
    raw_path = database_url.removeprefix("sqlite:///")
    database_path = Path(raw_path)
    if not database_path.is_absolute():
        database_path = (backend_dir / database_path).resolve()
    for suffix in ("", "-shm", "-wal"):
        candidate = Path(f"{database_path}{suffix}")
        if candidate.exists():
            candidate.unlink()



def _capture_preserved_counteroffers(
    db: Session,
) -> tuple[list[dict[str, object]], list[dict[str, object]]]:
    try:
        preserved = db.scalars(
            select(Challenge).where(Challenge.provenance != "demo_data")
        ).all()
    except OperationalError:
        db.close()
        return [], []

    account_ids = {challenge.challenger_account_id for challenge in preserved}
    accounts = [db.get(Account, account_id) for account_id in account_ids]
    preserved_account_payloads = [
        {
            "id": account.id,
            "handle": account.handle,
            "business_name": account.business_name,
            "service_area": account.service_area,
            "created_at": account.created_at,
        }
        for account in accounts
        if account is not None
    ]
    preserved_challenges = [
        {
            "challenger_account_id": challenge.challenger_account_id,
            "bidding_mode_at_submission": challenge.bidding_mode_at_submission,
            "price_minor": challenge.price_minor,
            "price_currency": challenge.price_currency,
            "billing_frequency": challenge.billing_frequency,
            "scope_included": challenge.scope_included,
            "scope_excluded": challenge.scope_excluded,
            "scope_extras": challenge.scope_extras,
            "setup_fee_minor": challenge.setup_fee_minor,
            "taxes_included": challenge.taxes_included,
            "supplies_included": challenge.supplies_included,
            "minimum_term": challenge.minimum_term,
            "other_conditions": challenge.other_conditions,
            "message_to_owner": challenge.message_to_owner,
            "availability": challenge.availability,
            "offer_expiry": challenge.offer_expiry,
            "site_visit_required": challenge.site_visit_required,
            "provenance": challenge.provenance,
            "submitted_at": challenge.submitted_at,
            "revised_at": challenge.revised_at,
        }
        for challenge in preserved
    ]
    db.close()
    return preserved_account_payloads, preserved_challenges



def _restore_preserved_accounts(
    preserved_accounts: list[dict[str, object]],
    db: Session,
) -> None:
    for payload in preserved_accounts:
        if db.get(Account, payload["id"]):
            continue
        db.add(Account(**payload))
    db.commit()



def _seed_demo_challenges(listing_id: str, db: Session) -> list[str]:
    first = submit_challenge(
        listing_id,
        "acc_challenger_1",
        {
            "price_minor": 187500,
            "billing_frequency": "monthly",
            "scope_included": ["vacuum", "trash", "restrooms", "3x weekly", "equipment"],
            "scope_excluded": [],
            "scope_extras": [],
            "supplies_included": True,
            "taxes_included": True,
            "message_to_owner": "Can start next month.",
            "provenance": "demo_data",
        },
        db,
    )
    second = submit_challenge(
        listing_id,
        "acc_challenger_2",
        {
            "price_minor": 195000,
            "billing_frequency": "monthly",
            "scope_included": ["vacuum", "trash", "restrooms", "3x weekly"],
            "scope_excluded": ["equipment included"],
            "scope_extras": [],
            "supplies_included": True,
            "taxes_included": True,
            "message_to_owner": "Equipment billed separately.",
            "provenance": "demo_data",
        },
        db,
    )
    return [first.id, second.id]



def _restore_preserved_challenges(
    listing_id: str,
    scope_version_id: str,
    preserved_challenges: list[dict[str, object]],
    db: Session,
) -> int:
    count = 0
    for payload in preserved_challenges:
        if db.get(Account, payload["challenger_account_id"]) is None:
            continue
        challenge = Challenge(
            listing_id=listing_id,
            scope_version_id=scope_version_id,
            challenger_account_id=payload["challenger_account_id"],
            bidding_mode_at_submission=payload["bidding_mode_at_submission"],
            price_minor=payload["price_minor"],
            price_currency=payload["price_currency"],
            billing_frequency=payload["billing_frequency"],
            scope_included=payload["scope_included"],
            scope_excluded=payload["scope_excluded"],
            scope_extras=payload["scope_extras"],
            setup_fee_minor=payload["setup_fee_minor"],
            taxes_included=payload["taxes_included"],
            supplies_included=payload["supplies_included"],
            minimum_term=payload["minimum_term"],
            other_conditions=payload["other_conditions"],
            message_to_owner=payload["message_to_owner"],
            availability=payload["availability"],
            offer_expiry=payload["offer_expiry"],
            site_visit_required=payload["site_visit_required"],
            provenance=payload["provenance"],
            submitted_at=payload["submitted_at"],
            revised_at=payload["revised_at"],
            is_active=True,
        )
        db.add(challenge)
        db.commit()
        db.refresh(challenge)
        get_or_refresh_challenger_evidence(challenge, db)
        count += 1
    return count



def _refresh_all_evidence(challenge_ids: list[str], db: Session) -> int:
    refreshed = 0
    for challenge_id in challenge_ids:
        challenge = db.get(Challenge, challenge_id)
        if challenge is None:
            continue
        get_or_refresh_challenger_evidence(challenge, db)
        refreshed += 1
    return refreshed


if __name__ == "__main__":
    main()
